Repository project-studying-dotnet/Streetcode-Server-September, pull requests merged in 2024-10, with the labels that each got.

#227 Feat/209/redis
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Text/GetAll/GetAllTextsHandler.cs
  Streetcode/Streetcode.BLL/Services/Cache/CacheService.cs
  Streetcode/Streetcode.BLL/Services/Cache/ICacheService.cs
  Streetcode/Streetcode.BLL/Streetcode.BLL.csproj
  Streetcode/Streetcode.WebApi/Extensions/SeedingLocalExtension.cs
  Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
  Streetcode/Streetcode.WebApi/Streetcode.WebApi.csproj
  Streetcode/Streetcode.XUnitTest/MediatRTests/Streetcode/Text/GetAllTextsHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/Services/CacheServiceTests.cs
Labels: enhancement, task

#244 Remove dependencies
  Streetcode/Streedcode.Identity/Controllers/AuthApiController.cs
  Streetcode/Streedcode.Identity/Data/AppDbContext.cs
  Streetcode/Streedcode.Identity/Exceptions/CustomException.cs
  Streetcode/Streedcode.Identity/Extensions/SeedingLocalExtension.cs
  Streetcode/Streedcode.Identity/Services/Realizations/CacheService.cs
  Streetcode/Streedcode.Identity/Streetcode.Identity.csproj
Labels: invalid

#260 Security Hotspot: Make sure that decompressing this archive file is safe
  Streetcode/Streetcode.WebApi/Utils/WebParsingUtils.cs
  Streetcode/Streetcode.XUnitTest/Util/WebParsingUtil/WebParsingUtilsTests.cs
Labels: security hotspot

#269 Implement docker
  Streetcode/.dockerignore
  Streetcode/Streedcode.Identity/Dockerfile
  Streetcode/Streedcode.Identity/Properties/launchSettings.json
  Streetcode/Streedcode.Identity/Streetcode.Identity.csproj
  Streetcode/Streetcode.WebApi/Dockerfile
  Streetcode/Streetcode.WebApi/Extensions/SeedingLocalExtension.cs
  Streetcode/Streetcode.WebApi/Properties/launchSettings.json
  Streetcode/Streetcode.WebApi/Streetcode.WebApi.csproj
  Streetcode/Streetcode.sln
  Streetcode/docker-compose.dcproj
  Streetcode/docker-compose.override.yml
  Streetcode/docker-compose.yml
  Streetcode/launchSettings.json
Labels: enhancement

#296 update GetImageByStreetcodeIdHandler
  Streetcode/Streetcode.BLL/MediatR/Media/Image/GetByStreetcodeId/GetImageByStreetcodeIdHandler.cs
Labels: bug

#295 Implement Email service
  Streetcode/Streedcode.Identity/Enums/EmailType.cs
  Streetcode/Streedcode.Identity/Models/AzureBus/AzureRegisterMailDto.cs
  Streetcode/Streedcode.Identity/Models/AzureBus/BaseMessage.cs
  Streetcode/Streedcode.Identity/Program.cs
  Streetcode/Streedcode.Identity/Services/Interfaces/IAzureBusService.cs
  Streetcode/Streedcode.Identity/Services/Realizations/AuthService.cs
  Streetcode/Streedcode.Identity/Services/Realizations/AzureBusService.cs
  Streetcode/Streedcode.Identity/Streetcode.Identity.csproj
  Streetcode/Streetcode.Email/Controllers/EmailController.cs
  Streetcode/Streetcode.Email/Dockerfile
  Streetcode/Streetcode.Email/Enums/EmailType.cs
  Streetcode/Streetcode.Email/Extension/ApplicationBuilderExtensions.cs
  Streetcode/Streetcode.Email/Messaging/AzureServiceBusConsumer.cs
  Streetcode/Streetcode.Email/Messaging/IAzureServiceBusConsumer.cs
  Streetcode/Streetcode.Email/Models/BaseMessage.cs
  Streetcode/Streetcode.Email/Models/SendMailDto.cs
  Streetcode/Streetcode.Email/Models/SmtpSettings.cs
  Streetcode/Streetcode.Email/Program.cs
  Streetcode/Streetcode.Email/Properties/launchSettings.json
  Streetcode/Streetcode.Email/Resources/EmailTemplates.cs
  Streetcode/Streetcode.Email/Services/EmailService.cs
  Streetcode/Streetcode.Email/Services/IEmailService.cs
  Streetcode/Streetcode.Email/Streetcode.Email.csproj
  Streetcode/Streetcode.Email/appsettings.Development.json
  Streetcode/Streetcode.Email/appsettings.json
  Streetcode/Streetcode.XUnitTest/IdentityMicroservice/AuthService/LoginAsyncTests.cs
  Streetcode/Streetcode.XUnitTest/IdentityMicroservice/AuthService/LogoutAsyncTests.cs
  Streetcode/Streetcode.XUnitTest/IdentityMicroservice/AuthService/RefreshJwtTokenTests.cs
  Streetcode/Streetcode.XUnitTest/IdentityMicroservice/AuthService/RegisterAsyncTests.cs
  Streetcode/Streetcode.sln
  Streetcode/docker-compose.override.yml
  Streetcode/docker-compose.yml
  Streetcode/launchSettings.json
Labels: enhancement

#302 fix/301/allow any origin
  Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
Labels: bug

#299 Feat/251/ci cd for deploy
  .github/workflows/deploy-identity.yml
  .github/workflows/deploy-webapi.yml
Labels: task
